### ISSUE TITLE
File watcher failed repeatedly and has been disabled

### ISSUE THREAD

**Issue by StoneMoe** [flathub/com.jetbrains.PyCharm-Professional#147]
This issue is also tracked at: https://youtrack.jetbrains.com/issue/PY-58235/PyCharm-File-watcher-failed-repeatedly-and-has-been-disabled

**Comment by StoneMoe** [comment]
maybe related: https://github.com/JetBrains/intellij-community/pull/2171

**Comment by freeseacher** [comment]
yep. I've seen this couple of times. but extremely rare in my setup. 
I was always thinking that is kind of bug in pycharm code itself

**Comment by StoneMoe** [comment]
Jetbrains doesn't want to fix it for third-party package, I'll close it for now
