### ISSUE TITLE
Running PyCharm fails with "FATAL:setuid_sandbox_host.cc(157)"

### ISSUE THREAD

**Issue by mityax** [flathub/com.jetbrains.PyCharm-Professional#167]
On fedora38, this error is raised when opening any project in the latest PyCharm Professional from Flathub:

> [0405/134622.238776:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/extra/jbr/lib/chrome-sandbox is owned by root and has mode 4755.

Then, PyCharm freezes for a few seconds and exits.

Prior to opening a project, no error is raised and the demo tour project also worked fine. On opening any other project however, this problem appears.

**Comment by freeseacher** [comment]
i've got the same results on latest linux mint. 
Also i've got the same troubles on phpstorm with latest updates. 
No matter of new ui or old. 
The only options i've found now to fix an issue is to remove settings directory in `~/.var/app/Pycharm...`

**Comment by mityax** [comment]
Doesn't work for me sadly

**Comment by FakeShemp** [comment]
The new Chromium sandbox needs zypak. See here for fix: https://github.com/flathub/com.jetbrains.PyCharm-Community/pull/534

**Comment by freeseacher** [comment]
lets check this one.
https://github.com/flathub/com.jetbrains.PyCharm-Professional/pull/169 

it is disabling isolation as proposed as workaround in upstream https://youtrack.jetbrains.com/issue/IDEA-313202

it's looks working for me. but i've got several issues trying make it work.
especially cursed was an error after update. 
```
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true  
```

it can be seen after running in debug 
```
flatpak run -v com.jetbrains.PyCharm-Professional
```
after it launch was stuck and i have to remove configs in `~/.var/app/com.jetbrains.PyCharm-Professional/`. 

not really sure was it an issue with build or my own attempts to fix it

**Comment by freeseacher** [comment]
merged. should be in next build
