### ISSUE TITLE
PyCharm 2023.1 crashes on Markdown files

### ISSUE THREAD

**Issue by domSB** [flathub/com.jetbrains.PyCharm-Professional#168]
In the previous version, everything was working fine. 

Now at 2023.1, I couldn't open a project at all. After deleting the Readme.md in the Repo and cloning again, it worked. 

Opening the same Markdown file from other projects, also resulted in a crash. 
Surprisingly, I can open other projects, that contain Markdown files, but as soon as I try to open them, PyCharm crashes. 

If someone can tell me, where to collect log-files, I can provide them.

Contents of the Markdown were:
```
# EnablingGraph

## My Notes

```

Currently working on a Fedora Linux 37 (Workstation Edition) with Flatpak 1.14.4

Opened the same Repo on a Windows-PC with no struggle.

**Comment by freeseacher** [comment]
yep. tnx for report. that looks like related to 
https://github.com/flathub/com.jetbrains.PyCharm-Professional/issues/167 

i'm on it.

**Comment by freeseacher** [comment]
merged should be in next build
