### ISSUE TITLE
Unable to connect to Docker daemon

### ISSUE THREAD

**Issue by rgegriff** [flathub/com.jetbrains.PyCharm-Professional#19]
Hiya! I am unable to connect the flatpak pycharm to the /var/run/docker.sock socket.

Based on what I saw in some other flatpak repos, I tried to run `sudo flatpak override --filesystem=/var/run/docker.sock com.jetbrains.PyCharm-Professional` and restart pycharm, but I am still running into the same issue.

**Comment by johanfleury** [comment]
On my system I had to expose `/run/docker.sock` (even if `/var/run` is a symlink to `/run`) for it to work.

Could you try running : `sudo flatpak override --filesystem=/run/docker.sock com.jetbrains.PyCharm-Professional`?

Just for information, if you want to reset previous overrides, you can run `sudo flatpak override --reset com.jetbrains.PyCharm-Professional` and if you want to show the current overrides, you can run `sudo flatpak override --show com.jetbrains.PyCharm-Professional`.

**Comment by rgegriff** [comment]
Thanks for the tips on reset and --show for the override command! That is helpful. 
I tried to add just `/run/docker.sock` as well as adding `/var/run/docker.sock` and am still having trouble connecting. Not sure what else might be the issue. My overrides look like this now:
```
[Context]
filesystems=/var/run/docker.sock;/run/docker.sock;
```
Alas, still no luck.

**Comment by johanfleury** [comment]
I’m not sure how I can help here as this works on my system.

Are you sure your user is allowed to talk to the docker daemon (e.g. by being in the `docker` group)?

**Comment by rgegriff** [comment]
Yep! That was something I checked as well. Pycharm is running as my user, and I am in the docker group. I even chowned the docker socket to my user as well. Still nothing :/

I wonder if there is something else I need to do in Pycharm. I have just been clicking "Invalidate Caches and Restart" anytime I make a change.

**Comment by rgegriff** [comment]
I don't know how or when things started working, but I just noticed that pycharm is now able to talk to the docker daemon. There were several reboots that happened between when I applied that change and now, so maybe that was it?

**Comment by johanfleury** [comment]
I really don’t know as I wasn’t able to reproduce on my side.

I’m happy it finally worked for you, I’m gonna close the issue for now, feel free to re-open if the issue persists.
