### ISSUE TITLE
Update to 2023.3.1

### ISSUE THREAD

**Issue by albertoridolfi** [flathub/com.jetbrains.PyCharm-Professional#244]
Current version on Flathub is 2023.3, meanwhile 23.3.1 has been released a week ago. Please update it. Thanks.

https://blog.jetbrains.com/pycharm/2023/12/2023-3-1/

**Comment by freeseacher** [comment]
Yep thx. i've done it today https://github.com/flathub/com.jetbrains.PyCharm-Professional/pull/243
