### ISSUE TITLE
Missing libusb

### ISSUE THREAD

**Issue by moonglaive** [flathub/com.jetbrains.PyCharm-Professional#264]
This is missing libusb which means pyusb is not able to function.

**Comment by freeseacher** [comment]
Yep, along with a couple thousand other libraries. 
Flatpak has different options, but the easiest one is to make an extension. You can check it out here: https://docs.flatpak.org/en/latest/extension.html. We've got an extension point set up over here: https://github.com/flathub/com.jetbrains.PyCharm-Professional/blob/master/com.jetbrains.PyCharm-Professional.yaml#L21

Personally i do it like this https://github.com/freeseacher/com.jetbrains.PyCharm.Extensions.Python310
