### ISSUE TITLE
PyCharm fails to remove the lock file at shutdown

### ISSUE THREAD

**Issue by blauigris** [flathub/com.jetbrains.PyCharm-Professional#272]
Dear all,

This is my first issue ever and english is not my native language, so please bear with me.

I have noticed that if I close pycharm and the shutdown the computer everything works beautifully. However, if I hit the shutdown button without closing pycharm first, then the next time I boot and try to start pycharm I am greeted with a message saying that I need to remove an stale .lock file located in the following path.

![image](https://github.com/flathub/com.jetbrains.PyCharm-Professional/assets/2472399/9feb4290-9d14-459e-8272-a68df7b2471c)

> /var/home/<username>/.var/app/com.jetbrains.PyCharm-Professional/config/JetBrains/PyCharm2024.1/.lock

I imagine that some stuff that is run when pycharm is closing is not run by systemd or whatever is in charge of the shutdown. I am using Fedora Silverblue 40 btw.

I it not a big deal, it is just sightly annoying, but I thought that maybe reporting this could be a way to show gratitude for your work.

Let me know if I can be of any help.

Best

Carles

**Comment by freeseacher** [comment]
Hi, thanks for the report. 
i personally have the similar issue with Pycharm. 
That is because of isolation Pycharm checks for pid and found that it is still exist. 
Run script is provided by the Pycharm itself and i don't want to change that script
