### ISSUE TITLE
add ssh socket?

### ISSUE THREAD

**Issue by freeseacher** [flathub/com.jetbrains.PyCharm-Professional#38]
git clonning is pretty common via ssh and using ssh agent is supported by pycharm so why not?

**Comment by johanfleury** [comment]
Is it actually a good idea to enable that by default?

I’m open to discussion on this topic, but I feel like enabling this kind of features by default defeats the purpose of sandboxing.

Also, one can be easily enable this locally using Flatseal or by running `flatpak override --socket=ssh-auth com.jetbrains.PyCharm-Professional` on the command line.
