### ISSUE TITLE
"No such file or directory" in home

### ISSUE THREAD

**Issue by samweisgamdschie** [flathub/com.jetbrains.PyCharm-Professional#54]
When using Pycharm Prof 2022.1 and using a project with a pipenv interpreter I always get this message when adding a new Interpreter.

OS: openSUSE tumbleweed
Flatpak Installation: as user

`"Failed to create interpreter"`

`Cannot run program "/home/user/.local/bin/pipenv" (in directory "/home/user/git/repo/path"): error=2, No such file or directory`

I also tried to 

`flatpak override --user --filesystem home com.jetbrains.PyCharm-Professional`

But without a difference. 

I tried it with the manual installation and it worked.

**Comment by samweisgamdschie** [comment]
Hello! Do you have any idea or solution for this problem? I made a fresh installation and tried it there with exactly the same outcome.

**Comment by samweisgamdschie** [comment]
Any hints? Do you need help?

**Comment by johanfleury** [comment]
If you have an idea, please have a go. I’ll be happy to review your PR as quickly as possible.

**Comment by samweisgamdschie** [comment]
Sorry, I am only a user and have no idea of how to create a flatpak. At least I release every restriction possible with flatseal. But sadly without any success.

**Comment by freeseacher** [comment]
looks like pipenv works now as intended
