### ISSUE TITLE
Python3.8?

### ISSUE THREAD

**Issue by andreasnuesslein** [flathub/com.jetbrains.PyCharm-Professional#9]
I might be in the wrong place here, since I don't quite understand the flatpak architecture yet.

Either way: when I browse to `/usr/bin/` within Pycharm (to select python3.8) I only see python3.7 (`python`, `python3` and `python3.7` but all) assuming a `/usr/lib/python3.7/` path that doesn't work with the fedora 32 beta that has python3.8  .. 

can you enable python3.8 or is this a beta-thing and will only fixed when Fedora 32 is stable?

cheers

**Comment by johanfleury** [comment]
Hi there.

This package uses the [Freedesktop SDK](https://gitlab.com/freedesktop-sdk/freedesktop-sdk) which ships with Python 3.7 ([master branch has Python 3.8](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/python3.bst)).

I don’t think there’s much I can do at this package level.

**Comment by andreasnuesslein** [comment]
Gotcha! Thank you for explaining :)
